name: Upload Chunked Data to Oracle Cloud

on:
  push:
    branches:
      - main
    paths:
      - datasets/**
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Generate OCI private key file
      run: |
        mkdir -p keys
        echo "${{ secrets.OCI_PRIVATE_KEY }}" > keys/oci-private-key.pem

    - name: Run upload script
      env:
        OCI_USER: ${{ secrets.OCI_USER }}
        OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
        OCI_TENANCY: ${{ secrets.OCI_TENANCY }}
        OCI_REGION: ${{ secrets.OCI_REGION }}
      run: |
        source venv/bin/activate
        python scripts/upload_chunk_data_to_oracle_cloud.py ./datasets/aldi-locations.csv aldi-locations axi7n4s6d44f
